### ISSUE TITLE
Find Venues

### ISSUE THREAD

**Issue by sawaka1** [sawaka1/hello-world#1]
# Venues
![Venue Example](http://crazyresto.weebly.com/uploads/2/6/1/2/26127029/2857402_orig.jpg)
## Shibuya
* [ ] Size
* [ ] Capacity
* [ ] Address

**Comment by dice** [comment]
Ooh @sawaka1 I like that space. :hamburger:

**Comment by dice** [comment]
@mmoris What do you think?

**Comment by sawaka1** [comment]
@minamiyamamori どうかな？

**Comment by mmoris** [comment]
:smile:

**Comment by dice** [comment]
* [ ] a
* [ ] b
* [ ] c

**Comment by mmoris** [comment]
# Mt.Fuji
![]　http://img03.ti-da.net/usr/k/a/t/katsujuku8317061/img_421614_8140289_5.jpg

**Comment by dice** [comment]
![github-octocat](https://cloud.githubusercontent.com/assets/676836/7507128/bde9b1ee-f4a5-11e4-9975-b3d9ec97651b.png)

**Comment by sawaka1** [comment]
@dice cute octocat!
